### ISSUE TITLE
Please support schema file

### ISSUE THREAD

**Issue by quangvo09** [ttpho/elixir-json-conver#9]
Thank you for making this awesome library.

Currently, I need to convert a given schema file to a phoenix task.

### Input schema file
```
defmodule Book do
  use Ecto.Schema

  schema "book" do
	field(:code, :string)
	field(:created_at, :string)
	field(:edition, :string)
	field(:price, :integer)
	field(:publisher, :string)
	field(:title, :string)
	field(:updated_at, :string) 
  end
end
```

### Output phoenix task
```
mix phx.gen.html ModuleBook Book book \
	code:string \
	created_at:string \
	edition:string \
	price:integer \
	publisher:string \
	title:string \
	updated_at:string
```

Hope you will implement this feature.

**Comment by ttpho** [comment]
@quangvo09 Thank you for your request. I will implement this request.

**Comment by ttpho** [comment]
@quangvo09
In this  task, I will do 
- Read schema file line by line
- Each line, use `Regex` to get :

> + module name 
> + schema name 
> + all fields: each field with name and type

For example, I use `Regex` to get the module name 


```elixir 
iex>regex = ~r"defmodule\s.*?(.*?)\sdo"
~r/defmodule\s.*?(.*?)\sdo/
iex> Regex.run(regex, "defmodule Book do")
["defmodule Book do", "Book"]
```
https://regex101.com/r/qs1alr/4

how about your opinion? 🙇

**Comment by ttpho** [comment]
I use Regex to get the schema name
https://regex101.com/r/qs1alr/5

I use Regex to get name and type
https://regex101.com/r/qs1alr/6

**Comment by quangvo09** [comment]
Hello @ttpho, I have just made some Regex patterns to parse the schema file:

### Module name
```
/defmodule\s+([0-9a-z_-]+)\s+do/gmi
```

### Schema name
```
/schema\s+"([0-9a-z_-]+)"\s+do/gmi
```

### Field name and field type
```
/field\s{0,}\(?\s{0,}:([0-9a-z_-]+),\s{0,}:([0-9a-z_-]+)\)?/gmi
```

Please try to apply it :)

**Comment by ttpho** [comment]
> Hello @ttpho, I have just made some Regex patterns to parse the schema file:
> 
> ### Module name
> ```
> /defmodule\s+([0-9a-z_-]+)\s+do/gmi
> ```
> 
> ### Schema name
> ```
> /schema\s+"([0-9a-z_-]+)"\s+do/gmi
> ```
> 
> ### Field name and field type
> ```
> /field\s{0,}\(?\s{0,}:([0-9a-z_-]+),\s{0,}:([0-9a-z_-]+)\)?/gmi
> ```
> 
> Please try to apply it :)

@quangvo09 thank you for your support :bow:

**Comment by quangvo09** [comment]
@ttpho I look forward to seeing this feature :)

**Comment by ttpho** [comment]
@quangvo09 Please help me check and review it.

**Comment by quangvo09** [comment]
@ttpho I have given some comments, please review it.
Thank you so much 😊
